
baseURL = "https://puzzleplorer.com/"
languageCode = "en-us"
title = "Puzzleplorer"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
